// ->> mutation에 어떤 기능들이 있는지 정리하는 목적으로 사용합니다.
export const REQUEST_BOARD_LIST_TO_SPRING = 'REQUEST_BOARD_LIST_TO_SPRING'
export const REQUEST_BOARD_TO_SPRING = 'REQUEST_BOARD_TO_SPRING'

export const REQUEST_PRODUCT_LIST_TO_SPRING = 'REQUEST_PRODUCT_LIST_TO_SPRING'
export const REQUEST_PRODUCT_TO_SPRING = 'REQUEST_PRODUCT_TO_SPRING'